### ISSUE TITLE
Wrong duration unit

### ISSUE THREAD

**Issue by stabl-gjn** [gengteng/axum-limit#1]
I noticed that you are using the `Duration::from_secs` for this constructor, while the `PER` is always given in milliseconds.
I think this should be `Duration::from_millis` instead.

https://github.com/gengteng/axum-limit/blob/ecb59d9f7448227cc511425a4f01b6c2a01961b4/src/lib.rs#L130

**Comment by gengteng** [comment]
Thank you for bringing up this issue! 😊

The problem with using `Duration::from_secs` has been fixed. The `refill()` method was refactored to use milliseconds instead of seconds to prevent division by zero errors when the refill duration is less than one second.

Additionally, a new unit test `limit_per_100_millis` was added to ensure the rate limiter correctly handles millisecond intervals.

Please feel free to test the latest version, and let me know if you encounter any further issues!

**Comment by stabl-gjn** [comment]
Hey @gengteng thanks so much for the quick fix.
Did some basic testing and this seems to work as expected now but i found two other strange behaviors while doing so (will create separate issues).

Btw the code is very clean and readable, made it very easy to understand what was going wrong :smile:
